### ISSUE TITLE
Dockerize Infoset-ng

### ISSUE THREAD

**Issue by Pr0x1m4** [PalisadoesFoundation/infosetDB#128]
Infoset-ng should be turned into an docker application to be better reussable and installed in applications such as [Garnet](https://github.com/PalisadoesFoundation/garnet) and others.

Dockerizing involves:
1. Adding working docker file to project
2. Adding project to docker registry

**Comment by Pr0x1m4** [comment]
This issue from garnet depends on this feature https://github.com/PalisadoesFoundation/garnet/issues/31

**Comment by Pr0x1m4** [comment]
@chenshuiluke

**Comment by Jhamali** [comment]
Can this be considered done? @Pr0x1m4

**Comment by Pr0x1m4** [comment]
Yuup, this can be closed as well
