### ISSUE TITLE
Replacing Infoset's Database Structure

### ISSUE THREAD

**Issue by Pr0x1m4** [PalisadoesFoundation/infosetDB#149]
Choose one:feature

#### User Story

As a user/data visualizer, I want to quickly and confidently collect data/data sets via web-scraping, locahost collecting or remote host fetching.

Infoset should facilitate all of this without requiring me to do most of the leg work. Instead of a rigid SQL structure already present in infoset, describing the database should be as flexible as actually writing an SQL file.

```sql
CREATE TABLE IF NOT EXISTS `weather_details` (
  `date` int(11) NOT NULL AUTO_INCREMENT,
  `temperature` varchar(255) DEFAULT NULL,
  `air_pressure` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`date`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=10001 ;
```
This database gets created at infoset's runtime and allows me to quite literally change, mold and alter infoset to accomadate any dataset that I wish to collect.

Considered Done
- [ ] Remove rigid SQL classes
- [ ] Allow for SQL file loading
- [ ] Provide default DB structure if custom SQL not provided

**Comment by Jhamali** [comment]
Was this done already?

**Comment by Pr0x1m4** [comment]
This was explored and discovered not to be feasible, the result of this was just to stick with one database strucutre albeit a simpler one, can be closed.
